name: Build Translator
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build React App
        run: |
          cd translator
          npm install
          npm run build
          cp -r dist/* .
      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add translator/
          git commit -m "Auto build translator app" || exit 0
          git push
